name: PowerShell Pester Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Pester 3.4.0
      run: |
        Install-Module Pester -RequiredVersion 3.4.0 -Force -Scope CurrentUser -SkipPublisherCheck
        Import-Module Pester -RequiredVersion 3.4.0

    - name: Run Pester tests in Clean Session
      run: |
        pwsh -NoProfile -Command "& {
          Import-Module Pester -RequiredVersion 3.4.0
          Invoke-Pester -Path .\Test-Get-AWSMetadata.ps1 -EnableExit
        }"
