# This workflow is disabled from auto-triggering.
# It is kept for reviewer reference and testing only on CI pipeline in future.
name: CI Pipeline (DISABLED)

# Prevent this workflow from being triggered automatically
on:
  workflow_dispatch:  # Manual trigger only

# Original jobs here
jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Pester 3.4.0
      run: |
        Install-Module Pester -RequiredVersion 3.4.0 -Force -Scope CurrentUser -SkipPublisherCheck
        Import-Module Pester -RequiredVersion 3.4.0

    - name: Run Pester tests in Clean Session
      run: |
        pwsh -NoProfile -Command "& {
          Import-Module Pester -RequiredVersion 3.4.0
          Invoke-Pester -Path .\Test-Get-AWSMetadata.ps1 -EnableExit
        }"
